[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "multisim"
version = "0.0.1"
description = "A package for simulating MEEG data"
authors = [
    { name = "Alex Lepauvre", email = "alex.lepauvre@gmail.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
docs = ["pydata-sphinx-theme", "nbsphinx", "ruff", "ipython"]
export = ["mne", "eeglabio"]

[project.urls]
Homepage = "https://github.com/AlexLepauvre/meeg_simulator"
Repository = "https://github.com/AlexLepauvre/meeg_simulator"

[tool.setuptools]
packages = ["multisim"]  # Automatically find the package

[tool.setuptools.package-data]
"multisim" = ["*.json", "*.csv"]  # Include additional data files if needed
